# Generated by Django 5.2.2 on 2025-06-28 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(max_length=255)),
                ('ingredientes', models.CharField(max_length=255)),
                ('modo_preparo', models.CharField(max_length=255)),
                ('tempo_preparo', models.IntegerField()),
                ('rendimento', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=255)),
                ('date_prato', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
